umisoft:
  jwt:
    secret: umisoft.cn
    minutes: 30
  avatar-disk-prefix-path: /Users/hujie/Downloads
  mybatis-plus:
    generator:
      global:
        author: hujie@umisoft.cn
        file-override: false
        base-result-map: false
      package:
        module-name: admin
        parent: cn.umisoft
      strategy:
        naming: underline_to_camel
        column-naming: underline_to_camel
        logic-delete-field-name: DELETED
        rest-controller-style: true
        controller-mapping-hyphen-style: true
        entity-lombok-model: true
        super-entity-columns:
          - id
          - deleted
          - createdBy
          - createdDate
          - modifiedBy
          - modifiedDate
        super-entity-class: cn.umisoft.admin.entity.UmiREntity
        super-service-class: cn.umisoft.admin.service.UmiService
        super-service-impl-class: cn.umisoft.admin.service.impl.UmiServiceImpl
        super-controller-class: cn.umisoft.admin.controller.UmiTController
        table-prefix:
          - T_
          - R_
spring:
  datasource:
    # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      url:
      username:
      password:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  redis:
    database: 0
    host:
    port:
    password:
mybatis-plus:
  configuration:
    # 开启查询结果【下划线转驼峰】
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # 支持统配符 * 或者 ; 分割
  type-enums-package: cn.umisoft.*.enum
